[package]
name = "feedscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.20.0"
atom_syndication = "0.12"
chrono = "0.4.38"
url = "2.5.2"
clap = {version ="4.5.13",features = ["derive"]}
